src/cli/mod.rs
src/run_checker/analysis.rs
src/run_checker/mod.rs
src/run_checker/snapshots/statistics-test-suite.json
src/run_checker/snapshots/statistics-test-suite_raw_reports.json
src/run_checker/tests.rs

e.g.
```json
[
{
"user": "repos",
"repo": "os-checker-test-suite",
"package": "os-checker-test-suite",
"raw_reports": [
{
"file": "examples/need-clippy-fix.rs",
"count": 1,
"fmt": [
"file: /rust/my/os-checker/repos/os-checker-test-suite/examples/need-clippy-fix.rs (original lines from 2 to 2)\n-    _ = (123); \n+    _ = (123);\n"
],
"clippy_warn": [],
"clippy_error": []
},
{
"file": "examples/need-fmt.rs",
"count": 1,
"fmt": [
"file: /rust/my/os-checker/repos/os-checker-test-suite/examples/need-fmt.rs (original lines from 1 to 1)\n-fn main() {    println!(\"from example\");\n+fn main() {\n+    println!(\"from example\");\n"
],
"clippy_warn": [],
"clippy_error": []
},
{
"file": "src/main.rs",
"count": 3,
"fmt": [
"file: /rust/my/os-checker/repos/os-checker-test-suite/src/main.rs (original …
```

feat(RawReportsOnFile): 更良好的详情信息、基于文件视角的 JSON 格式

---

.github/workflows/run.yml
Cargo.lock
Cargo.toml
assets/repos.json
os-checker-types/src/lib.rs
src/cli/mod.rs
src/config/deserialization.rs
src/config/deserialization/config_options.rs
src/config/mod.rs
src/db/db.rs
src/db/gh/mod.rs
src/db/mod.rs
src/db/types.rs
src/db/utils.rs
src/layout/mod.rs
src/output/mod.rs
src/run_checker/mod.rs
src/run_checker/packages_outputs.rs
src/run_checker/tests.rs
src/run_checker/utils.rs

close https://github.com/os-checker/os-checker/issues/101
对仓库完整检查结果的缓存键进行缓存，通过 `gh api` 查询仓库的最新 sha 来跳过实际仓库下载，与数据库记录的仓库 sha 的相匹配时，直接从数据库获取检查结果。
在缓存命中的情况下，减少了仓库下载、工具链安装和所有检查时间，最终在 1 秒钟之内得到一个仓库的检查结果。

feat: 仓库缓存查询优化

---

.github/workflows/run.yml
assets/repos.json
examples/batch.rs
os-checker-database/src/db/mod.rs
os-checker-database/src/targets/mod.rs
os-checker-types/src/checks.rs
os-checker-types/src/info.rs
os-checker-types/src/lib.rs
os-checker-types/src/prelude.rs
os-checker-types/src/table.rs
os-checker-types/src/tests.rs
src/cli/mod.rs
src/db/cache/mod.rs
src/db/db.rs
src/db/info/mod.rs
src/run_checker/mod.rs
src/run_checker/utils.rs

close https://github.com/os-checker/os-checker/issues/117
* 通过 db 子命令和 --start 和 --done 参数来控制每组检查的开始和结束，从而解决了分批检查识别首尾的问题；
* 添加 CHECKS 表，其中键为从 0 递增的 u32 值，值为这组检查的仓库的 InfoKey —— 可由这个值，去 INFO 表找到相应的检查命令缓存
* 重构 target 页面生成数据的逻辑

feat: 记录每组检查的 InfoKey

---

.github/workflows/run.yml
Makefile
assets/repos.json
os-checker-types/src/lib.rs
src/config/checker.rs
src/config/cmd.rs
src/config/deserialization.rs
src/config/deserialization/config_options.rs
src/config/mod.rs
src/config/resolve.rs
src/db/cache/type_conversion.rs
src/output/mod.rs
src/run_checker/lockbud.rs
src/run_checker/mod.rs
src/run_checker/rap.rs
src/run_checker/utils.rs
src/utils/installation.rs
src/utils/mod.rs

close https://github.com/os-checker/os-checker/issues/138
遗留问题：
* 和 lockbud 一样，诊断采用不可解析的日志形式输出，导致结果呈现不友好，并且无法精确到文件
* 目前只在 host target 上运行检查，因为 RAP 暂不支持转发 cargo check 参数
* -F 和 -M 两类检查目前必须是分开成 rap 两个命令，加上每次检查需要 cargo clean，这导致检查时间翻倍

feat: 集成 RAP 来检查 Use After Free 和 Memory Leakage 

---

.github/workflows/run.yml
assets/repos-ui.json
assets/repos.json
os-checker-types/src/lib.rs
src/config/checker.rs
src/config/cmd.rs
src/config/deserialization.rs
src/config/deserialization/config_options.rs
src/config/resolve.rs
src/db/cache/type_conversion.rs
src/output/mod.rs
src/run_checker/geiger.rs
src/run_checker/mod.rs
src/run_checker/utils.rs

close https://github.com/os-checker/os-checker/issues/154
由于 geiger 需要编译才能检测，这增加了检查时间和编译产物，Github Runner 再次遇到磁盘耗尽。
尝试剔除一些检查，依然磁盘耗尽，于是在 CI 上又耗费了一下午... （写集成的 Rust 代码也才不到 2 小时...）
最终只好检查部分仓库，暂不在这个 PR 中推送到 main database。

feat: 集成 cargo-geiger 来检测代码库中是否包含 unsafe Rust

---

.github/workflows/run.yml
Cargo.toml
Makefile
assets/repos-ui.json
assets/repos.json
os-checker-types/src/layout.rs
src/cli/mod.rs
src/config/deserialization.rs
src/config/mod.rs
src/layout/detect_targets.rs
src/layout/mod.rs
src/output/mod.rs
src/output/toolchain.rs
src/run_checker/mod.rs
src/run_checker/utils.rs

close https://github.com/os-checker/os-checker/issues/165
* 仓库名以逗号分隔，示例 `a/b,c/d`；plugin-cargo 应该每次只需要一个仓库 `a/b`
* 该命令会下载仓库、工具链：下载仓库工具链其实不是必须的，但目前它位于生成 layout 阶段，暂时不修改代码，因为运行测试需要下载工具链
* 只通过向 stdout 输出 JSON 格式，该格式可解析为 os-checker-types crate 中的 `Vec<ListTargets>` 
```rust
#[derive(Serialize, Deserialize, Debug)]
pub struct ListTargets {
pub user: XString,
pub repo: XString,
pub pkg: XString,
pub targets: Vec<String>,
}
```
* 会检查输入的仓库是否在配置文件中，如果不在，则产生 error：
```rust
Error: 
0: seL4/rust-sel4 is not in config repos:
{"AsyncModules/embassy-priority", "Azure-stars/elf_parser_rs", "Byte-OS/ByteOS", "Byte-OS/lose-net-stack", "Byte-OS/polyhal", "Godones/loongArch64", "Godones/rCoreloongArch", "Starry-OS/Starry", "Starry-OS/arm_gic", "Starry-OS/axprocess", "Starry-OS/dw_apb_uart", "Starry-OS/of", …
```

feat: layout 命令添加 `--list-targets` 参数，以获取给定仓库的 packages 和它们的 targets

---

.github/workflows/run.yml
Makefile
examples/batch.rs
src/cli/mod.rs

close https://github.com/os-checker/os-checker/issues/180

feat: support `OS_CHECKER_CONFIGS` which is used when `--config` is omitted

---

.github/workflows/run.yml
assets/repos.json
src/run_checker/mod.rs

该 PR 包含以下功能：
* 更新工具链来更新所有数据
* 使用 os-checker 自己维护的 cargo-outdated  https://github.com/os-checker/dockerfiles/pull/3
* close https://github.com/os-checker/os-checker/issues/196
* close https://github.com/os-checker/os-checker/issues/206
* close https://github.com/os-checker/os-checker/issues/222

feat: 更新默认工具链到 2024-12-24；使用 cargo-outdated fork

---

.github/workflows/run.yml
os-checker-database/src/file_tree/mod.rs
os-checker-database/src/utils.rs
src/config/resolve.rs
src/run_checker/mod.rs
src/run_checker/packages_outputs.rs
src/utils/mod.rs

* close https://github.com/os-checker/os-checker/issues/217
* 放宽 rap 的检查范围：从 x86_64-unknown-linux-gnu 到检测到的所有 targets 上运行
* 更新默认工具链到 nightly-2024-12-25：因为检查结果发生变化，但检查命令未改变

feat: cargo 诊断增加时间戳；rap 在检测到的 targets 上运行；更新默认工具链到 nightly-2024-12-25

---

.github/workflows/run.yml
assets/repos.json
src/layout/detect_targets.rs
src/layout/mod.rs
src/output/toolchain.rs
src/run_checker/mod.rs
src/run_checker/utils.rs
src/utils/installation.rs

close https://github.com/os-checker/os-checker/issues/216
此 PR 还增加了 `FORCE_RUN_CHECK` 环境变量，设置为 true 时，表示下载仓库之后，不读取缓存，直接运行检查命令；默认为 false，表示下载仓库后，查看缓存再决定是否运行检查命令。
如果不要安装某个 target，应把它放入配置文件的 no_install_targets 字段。

fix: 在仓库和 package 中指定的 targets 应追加到安装列表，而不是覆盖安装列表

---

.github/workflows/run.yml
assets/repos.json
os-checker-types/src/cache.rs
os-checker-types/src/config.rs
src/config/cmd.rs
src/config/cmd/tests.rs
src/config/deserialization.rs
src/config/deserialization/config_options.rs
src/config/deserialization/config_options/type_conversion.rs
src/config/deserialization/type_conversion.rs
src/config/mod.rs
src/config/resolve.rs
src/db/cache/mod.rs
src/db/cache/type_conversion.rs
src/layout/mod.rs

* close https://github.com/os-checker/os-checker/issues/242 （暂不准备实现 2 和 4）
* 解决一部分 https://github.com/os-checker/os-checker/issues/197#issuecomment-2564332096
```json
{
"user/repo": { "env": {"ENV1": "val1", "ENV2": "val2"} }
}
```
```json
"meta": {
"target_env": {
"target1": { "ENV1": "val" },
"target2": { "ENV2": "val" }
}
}
```
当环境变量重复时，3 覆盖 1。
环境变量被放入命令的缓存键中。

feat: 支持对检查命令设置环境变量

---

CHANGELOG.md
Cargo.lock
Cargo.toml
os-checker-database/Cargo.toml
os-checker-types/Cargo.toml

Features
* feat: cargo 诊断增加时间戳；rap 在检测到的 targets 上运行 ([#234](https://github.com/os-checker/os-checker/pull/234))
* feat: 增加配置文件指定的 target 源 ([#239](https://github.com/os-checker/os-checker/pull/239))
* feat: 支持对检查命令设置环境变量 ([#244](https://github.com/os-checker/os-checker/pull/244))
Fixes
* fix: ALL_TARGETS 通过的仓库计数 ([#236](https://github.com/os-checker/os-checker/pull/236))
* fix: layout 子命令应输出到文件而不是 stdout ([#247](https://github.com/os-checker/os-checker/pull/247))
* fix: 一旦启发式地找到确定的 target，不要默认添加 x86_64-unknown-linux-gnu ([#233](https://github.com/os-checker/os-checker/pull/233))
* fix: 在仓库和 package 中指定的 targets 应追加到安装列表，而不是覆盖安装列表 ([#238](https://github.com/os-checker/os-checker/pull/238))
* fix: 运行 rap 时指定 --target 参数 ([#231](https://github.com/os-checker/os-checker/pull/231))

feat: 发布 v0.5.0

---

.github/workflows/run.yml
assets/repos.json

close https://github.com/os-checker/os-checker/issues/220
修复结果：
给 ostool 的仓库提交了诊断修复： https://github.com/ZR233/ostool/pull/1 ，诊断变成
由于缺乏变量信息，暂时无法排查具体是什么问题（打开 https://github.com/os-checker/os-checker/issues/252 ）

ci: check ZR233/ostool with libudev-dev installed

---

.github/workflows/run.yml
assets/repos.json

close https://github.com/os-checker/os-checker/issues/218
安装 fuse 环境之后的检查结果：
在测试情况上：（添加到 https://github.com/os-checker/os-checker/issues/253 ）
* 一个单元测试正常运行并通过（但需要运行 gen_img.sh 生成文件镜像为测试做准备）；
* 还有一个是集成测试，需要两个终端才能测试（或者需要一个自动化测试流程来替代人工测试）。
向 yuoo655/ext4libtest 提交诊断修复，见： https://github.com/yuoo655/ext4libtest/pull/1

ci: install libfuse-dev fuse3 libfuse3-dev for yuoo655/ext4libtest

---

.github/workflows/run.yml
assets/repos.json
src/run_checker/mod.rs

close https://github.com/os-checker/os-checker/issues/293
修复前： `error: unsupported rustdoc format v39 for file`
修复后：

feat: update semver-checks to support v39 rustdoc JSON format

---

src/run_checker/lockbud.rs

Change the date of lockbud report parser from 2024 to 2025.

fix: update lockbud report parser's date to 2025

---

src/cli/mod.rs
src/layout/mod.rs

`os-checker layout --no-layout-error` skips any package that is unable to compile when `cargo metadata` is invoked

Feat: add `--no-layout-error` layout subcommand option

---

Cargo.lock
Cargo.toml
examples/batch.rs
os-checker-database/Cargo.toml
os-checker-database/src/main.rs
os-checker-types/src/config.rs
src/cli/mod.rs
src/config/deserialization.rs
src/config/deserialization/config_options.rs
src/config/deserialization/config_options/type_conversion.rs
src/config/mod.rs
src/layout/detect_targets.rs
src/layout/mod.rs
src/layout/tests.rs
src/run_checker/mod.rs
src/utils/mod.rs

This PR
* removes single and batch features in  os-checker-database
* os-checker run subcommand adds --no-layout-error
* applies --no-layout-error
* input JSON supports meta.only_pkg_dir_globs field
* batch CLI adds --no-upload option

Feat: add `run --no-layout-error` and JSON input's `meta.only_pkg_dir_globs`

---

os-checker-types/src/config.rs
src/config/deserialization.rs
src/config/deserialization/config_options.rs
src/config/deserialization/config_options/type_conversion.rs
src/config/mod.rs
src/run_checker/mod.rs

This PR
* add `meta.rerun` in config JSON
* close https://github.com/os-checker/os-checker/issues/329
* this breaks cache format
* handle fmt, clippy, and mirai panic errors as Cargo error ouput

Feat:  support `meta.rerun` in config JSON

---

src/config/mod.rs
src/config/uri.rs
src/db/info/local.rs
src/db/info/mod.rs
src/layout/targets/mod.rs
src/run_checker/mod.rs
src/utils/scan_for_targets.rs

close https://github.com/os-checker/os-checker/issues/318
NOTE: the last two parent folder names are `user/repo`,
even though the user may donesn't make sense.
So local projects are better put into a folder name __local
to indicate the name doesn't correspond to a github user.

Feat: Support local project checking and caching

---

src/cli/mod.rs
src/run_checker/mod.rs
src/run_checker/packages_outputs.rs

close https://github.com/os-checker/os-checker/issues/340
for 1: each resolve has been already logged with a pkg name and dir, so no need to add anything
for 2: the target logging is removed in a previous commit
This PR mainly adds progress report through various numbers
```rust
len_resolves = %(len_resolves.red().bold()),
len_finished_resolves = %(len_finished_resolves.red()),
len_group_by_checker = %(len_group_by_checker.yellow().bold()),
idx_checker = %(idx_checker.yellow()),
current = ?(checker.blue().bold()),
len_checker_resolves = %(len_checker_resolves.blue().bold()),
idx_resolve = %(idx_resolve.blue())
```

Chore: make resolve logging prettier and with progress numbers

---

.github/workflows/run.yml
examples/batch.rs
os-checker-database/examples/lockbud/mod.rs
os-checker-types/src/config.rs
src/cli/mod.rs
src/config/deserialization.rs
src/config/deserialization/config_options.rs
src/config/deserialization/config_options/type_conversion.rs
src/config/mod.rs
src/db/db.rs
src/db/info/mod.rs
src/db/info/read_cache.rs
src/db/mod.rs
src/run_checker/mod.rs

This PR
* adds `meta.use_last_cache` in JSON config
* closes https://github.com/os-checker/os-checker/issues/344
* if a cache is found in db, use that info without doing the query again
* adds `--use-last-cache` that will override the settings by enabling `meta.use_last_cache` for all repos in config
* adjusts batch command to support forward os-checker run arguments verbatim via `-- arg1 arg2 ...`
* fixes lockbud's CondvarDeadlockDesciption bugkind in convert_repo_json
* closes https://github.com/os-checker/os-checker/issues/348

Feat: add `meta.use_last_cache` in JSON config and `--use-last-cache` in run subcommand

---

src/db/db.rs
src/db/info/read_cache.rs
src/layout/audit.rs
src/layout/detect_targets.rs
src/layout/mod.rs
src/layout/targets/mod.rs
src/utils/mod.rs

This PR
* `meta.only_pkg_dir_globs` takes a relative path pattern to filter in package Cargo.tomls, instead of filtering in folders
* close https://github.com/os-checker/os-checker/issues/337
*  repects cargo_tomls in `Layout::packages`
* closes https://github.com/os-checker/os-checker/issues/352

Fix: `meta.only_pkg_dir_globs` filters in Cargo.toml paths; `Layout::packages` respects cargo_tomls 

---

os-checker-types/src/config.rs
src/config/deserialization.rs
src/config/deserialization/config_options.rs
src/config/deserialization/config_options/type_conversion.rs

This PR 
* closes https://github.com/os-checker/os-checker/issues/345
* adds `meta.run_all_checkers` in JSON config, useful when setting it to false to disable all checkers
* `run --run-checkers` is not implemented for simplicity
* the new field should work with `cmds.checker`, especially as the following setting shows
```json
{
"user/repo": {
"meta": {
"run_all_checkers": false
},
"cmds": {
"checker1": true
}
}
}
```

Feat: support `meta.run_all_checkers` in JSON config

---

.github/workflows/run.yml
README.md
assets/repos.json
src/config/checker.rs
src/config/resolve.rs
src/run_checker/mod.rs
src/run_checker/utils.rs
src/utils/env_var.rs
src/utils/installation.rs
src/utils/mod.rs

This PR
* auto installs targets on toolchain required by AtomVChecker 
* closes https://github.com/os-checker/os-checker/issues/374
*  adjusts `FORCE_RUN_CHECK` to accept a set of checkers, such as `tool1,tool2`, which is handy when rerunning all checks from a specified checker

Fix: auto install targets on toolchain required by AtomVChecker; adjusts `FORCE_RUN_CHECK` to accept a set of checkers
